sudo: required
git:
  depth: false
matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 5.0
      dist: xenial
      install:
        - cd FightCore.Bot
        - dotnet restore
      before_script:
        # Script to expose the dotnet CLI tools.
        - export PATH="$PATH:$HOME/.dotnet/tools"
      script:
        # Run restore to restore the NuGet packages
        - dotnet restore
 
        - dotnet build

        - dotnet publish FightCore.Bot/FightCore.Bot.csproj --self-contained true --runtime linux-x64 -c Release

        - cd FightCore.Bot/bin/Release/netcoreapp3.1/linux-x64

        - tar -zcf Bot-Linux-x64.tar.gz publish/

      deploy:
        provider: releases
        api_key: $TOKEN
        file: "Bot-Linux-x64.tar.gz"
        skip_cleanup: true
        on:
          tags: true
      global:
        # Some global settings to make the experience better,
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
        - DOTNET_CLI_TELEMETRY_OPTOUT=1
      cache:
        directories:
          # Cache the NuGet and SonarCloud folders.
          - "$HOME/.nuget/packages"
          - "$HOME/.local/share/NuGet/Cache"
          - "$HOME/.sonar/cache"